### ISSUE TITLE
undefined symbol: _ZN3c1021throwNullDataPtrErrorEv

### ISSUE THREAD

**Issue by hnyls2002** [flashinfer-ai/flashinfer#382]
Version: build wheels from the latest head.
Python: 3.10.12
NVCC: 12.1
torch: 2.3.1

**Comment by yzh119** [comment]
Another similar issue: https://github.com/pytorch/executorch/issues/3797

**Comment by hnyls2002** [comment]
Sorry, this is due to my wrong compiling env.

**Comment by GrahamTheCoder** [comment]
![image](https://github.com/user-attachments/assets/f8f6f742-60bd-441c-9c48-656e0b1b8be9)

For me, it was that I was using wsl2 (windows subsytem for linux).
It tries to be helpful by converting paths within the %PATH% variable in windows putting them in $PATH
This is unhelpful since the files it points to are built for windows, not linux. So in /etc/wsl.conf you'll need to add 
```
[interop]
appendWindowsPath = false
```
Then do wsl --shutdown from the host. When you restart, `echo $PATH` to check things now look sane (much less in your path, and only linux things, not mounted paths back to windows files)
Now you'll need to thoroughly nuke any environments you had set up which were polluted when windows versions of npm, python etc. where trying to get involved previously. You'll also need to install sane versions of those tools (e.g. using conda and nvm) since the distro you have in WSL will inevitably have ancient unsupported ones that pretend to work up to a point then spit out errors.

**Comment by serihiro** [comment]
I faced this issue and in my case the root cause was because I specified wrong torch version.
I am using `poetry` and `torch` 2.4.0+cu121, then the following configuration worked for me.

```toml
[[tool.poetry.source]]
name = "flashinfer_cu121_torch24"
url = "https://flashinfer.ai/whl/cu121/torch2.4"
priority = "explicit"

[tool.poetry.dependencies]
flashinfer = { version = "0.1.6", source = "flashinfer_cu121_torch24" }
```

I hope this is helpful for someone.
